import {ACTION_APPFORMS_PREFIX} from '../constants';

export const ACTION_REGISTER_PREFIX = 'register.';
export const ACTION_REGISTER_SET_PASSWORD_TYPE = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.set_password`;
export const ACTION_REGISTER_SET_PASSWORD_KEY = 'password';
export const ACTION_REGISTER_SET_CONFIRM_PASSWORD_TYPE = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.set_confirm_password`;
export const ACTION_REGISTER_SET_CONFIRM_PASSWORD_KEY = 'confirmPassword';
export const ACTION_REGISTER_SET_EMAIL_TYPE = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.set_email`;
export const ACTION_REGISTER_SET_EMAIL_KEY = 'email';
export const ACTION_REGISTER_SET_NAME_TYPE = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.set_name`;
export const ACTION_REGISTER_SET_NAME_KEY = 'name';
export const ACTION_REGISTER_SET_ERRORS_TYPE = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.set_errors`;
export const ACTION_REGISTER_RESET_FORM = `${ACTION_APPFORMS_PREFIX}${ACTION_REGISTER_PREFIX}type.reset_form`;
